### ISSUE TITLE
[OPAM] 2.0

### ISSUE THREAD

**Issue by GemmaG** [ocamllabs/Projects#1]
Based on [(#2580)](https://github.com/ocaml/opam/issues/2580#issuecomment-240445901)

 - [x] do not force tests of recursive dependencies (related to [(#2277)](https://github.com/ocaml/opam/issues/2277) and [(#2190)](https://github.com/ocaml/opam/issues/2190))
 - [ ] integrated documentation. Need state update hooks or persistent event stream.
 - [x] incremental builds: [(#2596)](https://github.com/ocaml/opam/issues/2596) described something very useful to speed-up incremental rebuild of pinned packages (that we can really use with local switches + local package rebuild commands to have a nice dev workflow)
- [x] local switches (related to [(#1595)](https://github.com/ocaml/opam/issues/1595))
 - [x] better opam query
 - [ ] bundle/snapshot (related to [(#929](https://github.com/ocaml/opam/issues/929) and [existing hacks](https://github.com/samoht/vpnkit/blob/845dbd7c27de620bbacc78123def9942c31e0035/opam/update-upstream.sh))
 - [ ] [local packages](https://gist.github.com/samoht/2188fbd01b1d40a3e2063f3a270bf8fd)
 - [ ] [bundles](https://gist.github.com/samoht/54c5aaa7429a68d27fbe66515bea1c7b)
 - [ ] more variables exposing OS constraints. See [comment](https://github.com/ocaml/opam/issues/2580#issuecomment-240445901)

**Comment by AltGr** [comment]
Seems I don't have the credentials to tick the boxes, but I think 1., 3., 3.1. and 4. can be considered done.
1. Done

2. needs some design, should be straightforward once the interface is decided. In the meantime, can probably be prototyped using the existing hooks.

3. Done
   1. Done

4. Done (well depends what the reference for "better" is, but it should be pretty flexible now; the beta period is exactly when specific missing parts should be pointed out, if any.)

5. Deployment bundles are planned, but that will probably be for 2.1

6. There is some support for local packages through `--inplace-build`;  the rest is just query stuff or sugar over automatically pinning the package then installing with that option, so my opinion is that the bricks to allow experiments and designing the new workflows are here, and we can refine the interface over the beta period or for the next version

7. Reproducible switches: export files do part of the job; @dbuenzli's [proposal](https://github.com/ocaml/opam/issues/2532) is also close to this. This is really orthogonal to the rest of the features (except maybe binary/deployment bundles) and needs some more design discussions, and once we have a format we should commit to it long-term, so I wouldn't rush it.

8. Variables exposing OS constraints: provided there is a simple way to get the values of these variables, they can now be defined through global configuration. This is mostly a matter of choosing what needs to be defined.

**Comment by GemmaG** [comment]
I've given you write access now @AltGr - thanks!
